### ISSUE TITLE
Add LICENSE and NOTICE file

### ISSUE THREAD

**Issue by joenap** [traviscrawford/airflow-pex-example#1]
Hi Travis! We made a ton of progress with the Airflow/pants integration. I wanted to open a PR for your review, but I was asked to first reach out about the license. I was told that without an explicit LICENSE and NOTICE file, we have to assume that all rights are reserved. I’ll be able to submit my diff if we can get either the Apache or MIT license in the repository. Thanks again for all your help.

**Comment by traviscrawford** [comment]
This is now licensed via the apache license. Can you clarify what you mean by a notice file? Can you point me at an example?

**Comment by joenap** [comment]
Travis, super thrilled to get this going! Julien pointed me to the file in parquet as an example:

https://github.com/apache/parquet-mr/blob/master/NOTICE

**Comment by joenap** [comment]
Here's one I put together. It's a lot more succinct:
https://github.com/joenap/airflow-base/blob/master/NOTICE

That seemed to suffice for me in the past. Here's the official Apache doc:
http://www.apache.org/dev/licensing-howto.html
